Preserve search state on reload
pwmt/zathura pull request #649
Opened 2024-07-30 18:43 UTC by fcolona

With this, when reloading the document, the search state is preserved, including the search string and the search highlight. 

Closes #598

2024-08-10 19:32 UTC, sebastinas commented
Please rebase on top of develop.

2024-10-19 22:58 UTC, fcolona commented
Hi @sebastinas,
I forgot to tell you that I did the rebase and the PR was ready for review. Could you take a look at it when you have some time? Thank you!

2025-10-03 14:48 UTC, unrelated-stardust commented
What is left to do to merge this pull request? I'd like to help.

2025-10-04 07:59 UTC, sebastinas requested changes

2025-10-04 07:59 UTC, sebastinas commented on zathura/commands.c
> +  strcpy(zathura->global.search_string, input);
This is missing the length of the string.

2025-10-04 07:59 UTC, sebastinas commented on zathura/shortcuts.c
> +    if (zathura->document == NULL || strlen(zathura->global.search_string) == 0) {
First, this function should be static. Second, it is never called with document == NULL - otherwise the call site is buggy. The string length check could also be done at the call site where it is checked if search_string != NULL.

2025-10-04 21:27 UTC, fcolona commented
Hi @unrelated-stardust, thanks for picking this up. And thanks to @sebastinas for the review. You are right about the `strcpy` issue, but I was looking at the dynamic memory allocation code for the `zathura->global.search_string` and I thought that maybe we could replace the whole if/else allocation/reallocation logic and the `strcpy` with the `g_strdup` function. What do you think? It would be something like this:

```
  g_free(zathura->global.search_string);
  zathura->global.search_string = g_strdup(input);
  if(zathura->global.search_string == NULL){
    return false;
  }
```

2026-09-08 11:18 UTC, sebastinas commented
Sorry for taking so long to respond. I have rebased your PR and adopted it to the changes on develop.

2026-09-08 11:18 UTC, closed without merging